### ISSUE TITLE
HOW TO USE uSDX_TX code 

### ISSUE THREAD

**Issue by www97221** [kaefe64/Arduino_uSDX_Pico_FFT_Proj#7]
Thank you for sharing your work. I have an unclear question about how to use the code in the uSDX-TX folder? How to debug or test the phase using code? Is there a specific testing process in uploading to the RP2040 microprocessor or Arduino Pro min board?

**Comment by kaefe64** [comment]
Hello www97221

The uSDX-TX folder was created to try the "Amplitude/Phase" transmission, similar to the uSDX, using the RP2040.
It is not a final software, it is just a test. It reads the audio and transmits using "Amplitude/Phase" code from PE1NNZ uSDX converted to RD2040.
It is just for transmission and the frequency is fixed in the code: freq = 7100000;
Look the comments at beginning of "uSDX_TX.ino" file to know the input/output pins.

I hope it helps to answer your questions.
Have fun
Klaus F
PY2KLA
